### ISSUE TITLE
No encoding declared

### ISSUE THREAD

**Issue by tymurbaniak** [tutajrobert/grot#1]
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    import bmp, prep, tools, solver, postpro
  File "/mnt/c/Users/user/Documents/Python Projects/GRoT/grot/bmp.py", line 15
SyntaxError: Non-ASCII character '\xc4' in file /mnt/c/Users/user/Documents/Python Projects/GRoT/grot/bmp.py on line 15, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

On Win10 environment

**Comment by tutajrobert** [comment]
There is no such information, but this project is written in python3. Default encoding for python3 is utf-8 and I don't deviate from this standard - so no encoding is declared. I hope that this decision is not considered as lack of style in coding. Regards!

**Comment by tymurbaniak** [comment]
In this case I think, there should be README file with informations about runtime environment.

**Comment by tutajrobert** [comment]
Great advice. Will be done! Thanks
