### ISSUE TITLE
Strange syntx error with unpacked argument

### ISSUE THREAD

**Issue by tymurbaniak** [tutajrobert/grot#2]
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    import bmp, prep, tools, solver, postpro
  File "/mnt/c/Users/user/Documents/Python Projects/grot/bmp.py", line 128
    {**nmerge_list[i], **nmerge_list[i - 1]})
      ^

Environment: python 3.4.3 bash on windows 10, but also on Debian with python 3.4.2

**Comment by tutajrobert** [comment]
** It is new dictionary unpacking operator introduced in python 3.5, please go to the webstie below:
https://docs.python.org/3/whatsnew/3.5.html
To get rid of version problems, I will prepare the readme file for this repository, which will indicate the use of python 3.5
