### ISSUE TITLE
Path to projects and results folder as an atribute

### ISSUE THREAD

**Issue by tymurbaniak** [tutajrobert/grot#4]
Path to projects and results directory passed to GROT as an attribute would be really useful, especially when using GROT with 3rd party software. I think the best way to achieve this would be writing directory paths after some kind of letter atribute, for example:
`python3 run.py -p /results/directory /project/directory`
This way the user could run GROT with default paths, when writing command
`python3 run.py`

**Comment by tutajrobert** [comment]
Done in grot-serv fork. Cheers!
